@echo off
echo Đang thêm bản nâng cấp Admin Email Whitelist & Công tắc chuyển đổi giao diện...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit Whitelist Admin Email...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Cấu hình Admin Email Whitelist cho kieuthi14@gmail.com và thêm Nút Công tắc chuyển đổi giao diện Admin / Học sinh 1-Click trên Sidebar"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
