@echo off
echo Đang thêm bản sửa lỗi cú pháp AuthContext.jsx...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit Sửa cú pháp...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Sửa khẩn cấp lỗi cú pháp Syntax Error dính chữ font-sans trong AuthContext.jsx"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
