@echo off
echo Đang thêm bản nâng cấp mở quyền truy cập Admin Dashboard...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit nâng cấp Admin...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Mở tự do Route /admin/dashboard, thêm Nút bấm Admin nổi bật trên Sidebar và khởi tạo Mock Data sinh động cho Ban Giám khảo"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
