@echo off
echo Đang thêm bản nâng cấp Đồng bộ Dữ liệu Phản tư & Bảo mật Admin RBAC...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit Phân quyền Admin & Refresh Data...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Đồng bộ dữ liệu Phản tư từ học sinh sang Admin kèm nút Refresh và Bảo mật phân quyền Role-Based Access Control cho trang Admin"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
