@echo off
echo Đang thêm bản sắp xếp lại menu Sidebar...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit sắp xếp Sidebar...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Sắp xếp lại thứ tự Sidebar menu chính đưa Lộ trình Hướng nghiệp lên vị trí thứ 2"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
