@echo off
echo Đang thêm dữ liệu Smart Fallback cho bài test và danh mục...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit cập nhật...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Thêm bộ dữ liệu Smart Fallback cho Holland Test, Major Explorer và University Explorer"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
