@echo off
echo Đang thêm bản nâng cấp Hướng dẫn tự tra cứu trường...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit nâng cấp...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Cập nhật mục Trường tham khảo & Hướng dẫn tự tra cứu trọn bộ các trường trong trang Chi tiết Ngành học"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
