@echo off
echo Đang thêm bản chuẩn hóa Vercel Deployment...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit chuẩn hóa Vercel...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Bổ sung fallback thông số kết nối Supabase sẵn sàng cho Vercel Production Deploy"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
