@echo off
echo Đang thêm các thay đổi sửa lỗi...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo bản commit vá lỗi...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Sửa lỗi thiếu import ArrowRight tại StudentDashboard"
echo Đẩy bản vá lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
