@echo off
echo Đang thêm bản nâng cấp Hybrid Sync...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit nâng cấp...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Nâng cấp cơ chế Hybrid Sync cho Lộ trình và Đặt lịch tư vấn"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
