@echo off
echo Đang thêm bản nâng cấp Debias AI Feedback...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit nâng cấp Khung AI Feedback...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Nâng cấp Khung Đánh giá & Nhận xét Phản tư AI (Debias AI Feedback) trong Card bản ghi Ma trận Phản tư"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
