@echo off
echo Đang thêm bản hoàn thiện Admin Dashboard ghép nối dữ liệu Supabase DB...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit Admin Dashboard ghép nối dữ liệu...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Hoàn thiện Admin Dashboard truy vấn ghép nối dữ liệu profiles, metacognitive_matrix, test_results an toàn từ Supabase RLS DB kèm nút Làm mới dữ liệu"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
