@echo off
echo Đang thêm bản chuẩn hóa Lộ trình 3 khối lớp...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit chuẩn hóa...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Chuẩn hóa Lộ trình Hướng nghiệp 3 khối lớp đồng bộ bước Trắc nghiệm Holland và Bảng Phản tư"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
