@echo off
echo Đang thêm bản nâng cấp trang Trắc nghiệm Holland...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit nâng cấp...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Nâng cấp trang Trắc nghiệm Holland bổ sung Banner Lời nhắc phản tư (Metacognitive Prompt) và Thang đo 4 mức (Likert Scale)"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
