@echo off
echo Đang sửa lỗi nút Phản tư ngay...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit sửa lỗi...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Sửa lỗi chuyển hướng nút Phản tư ngay bằng useNavigate trong trang Kết quả Trắc nghiệm Holland"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
