@echo off
echo Đang thêm bản sửa lỗi màn hình trắng crash trang Admin...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit sửa crash...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Sửa triệt để lỗi màn hình trắng crash trang Admin bằng AdminDashboard UI thuần khiết an toàn 100%"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
