@echo off
echo Đang thêm bản nâng cấp Dữ liệu thực tế Supabase DB cho Admin Dashboard...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit Supabase Real Data...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Thay thế hoàn toàn Mock Data bằng Dữ liệu thực tế từ CSDL Supabase (profiles, metacognitive_matrix, test_results) trong AdminDashboard"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
