@echo off
echo Đang thêm kịch bản SQL Seed Data mới...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit cập nhật schema.sql...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Cập nhật kịch bản SQL schema.sql nạp 100% dữ liệu thực cho Supabase DB"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
