@echo off
echo Đang thêm bản cập nhật Khớp nối dữ liệu Data Mapping cho Admin...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit Khớp nối Dữ liệu Admin...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Cập nhật logic truy vấn và khớp nối dữ liệu Data Mapping thực tế từ Supabase giữa profiles và metacognitive_matrix trong AdminDashboard"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
