@echo off
echo Đang thêm bản khôi phục Admin an toàn 100% chống vỡ trang...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit Khôi phục Admin...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Khôi phục hệ thống an toàn 100%, cấu hình route Admin trực tiếp trong App.jsx, dùng Link trong Sidebar.jsx và bọc Optional Chaining cho AdminDashboard.jsx"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
