@echo off
echo Đang thêm bản nâng cấp Lộ trình Hướng nghiệp 3 khối lớp...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit nâng cấp Lộ trình...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Nâng cấp hệ thống Lộ trình Hướng nghiệp Tối ưu cho cả 3 khối lớp 10, 11, 12 với Tab điều hướng tự động nhận diện"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
