@echo off
echo Đang thêm tính năng Ma trận Phản tư (Debias)...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit thêm mục Sidebar mới...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Thêm trang mới Ma trận Phản tư (Debias) và bổ sung item vào Sidebar"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
