@echo off
echo Đang thêm bản bảo mật ẩn nút Admin cho Học sinh...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit Bảo mật ẩn nút Admin...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Bảo mật và ẩn hoàn toàn nút Admin đối với học sinh trên Sidebar, bảo vệ route /admin/dashboard bằng AdminProtectedRoute"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
