@echo off
echo Đang thêm bản nâng cấp trang Chi tiết Ngành học...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit nâng cấp trang chi tiết...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Bổ sung Khung Thách thức & Mặt tối thực tế và Nút Phản tư nhanh vào trang Chi tiết Ngành học (Major Detail Page)"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
