@echo off
echo Đang thêm bản tinh chỉnh tên gọi Bảng Nhìn Lại & Kiểm Tra Chọn Nghề...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit tinh chỉnh...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Tinh chỉnh tên gọi Bảng Nhìn Lại & Kiểm Tra Chọn Nghề (Phản tư) bình dị dễ hiểu cho học sinh"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
