@echo off
echo Đang thêm bản hoàn thiện Ma trận Phản tư (Debias Matrix)...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit hoàn thiện tính năng...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Hoàn thiện giao diện và logic Bảng Ma trận Phản tư Chọn nghề (Debias Matrix)"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
