@echo off
echo Đang thêm bản sửa nút bấm Admin và trang AdminDashboard...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit sửa nút Admin...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Sửa triệt để nút bấm Admin Sidebar bằng useNavigate và tạo trang AdminDashboard hoàn chỉnh với nút Xuất dữ liệu Excel/CSV"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
