@echo off
echo Đang thêm bản cập nhật link Cổng tuyển sinh Bộ GD&ĐT...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit cập nhật...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Cập nhật link Cổng tuyển sinh chính thức Bộ GD&ĐT (tuyensinh.thi.moet.gov.vn) mở tab mới an toàn trong trang Chi tiết Ngành học"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
