@echo off
echo Đang thêm bản nâng cấp Thuật toán 4 Bẫy Tư Duy Chọn Nghề...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit Chẩn đoán 4 Bẫy Tư Duy...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Nâng cấp Thuật toán Chẩn đoán 4 Bẫy Tư Duy Chọn Nghề với ngôn ngữ dễ hiểu cho học sinh và đồng bộ Nhận xét AI"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
