@echo off
echo Đang thêm bản vá bảo mật và chống lặp redirect...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit vá lỗi...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Sửa lỗi RLS profile và chống vòng lặp redirect lặp vô tận tại AuthContext và App"
echo Đẩy bản cập nhật lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
