@echo off
echo Đang thêm bản nâng cấp Đánh giá sự thay đổi quyết định sau Phản tư...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit nâng cấp...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Bổ sung tính năng Đánh giá sự thay đổi quyết định sau Phản tư (Post-Reflection Decision Tracking) và Biểu đồ thống kê trên Admin Dashboard"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
