@echo off
echo Đang thêm bản nâng cấp Chẩn đoán Thiên kiến Tự động...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit Chẩn đoán Thiên kiến...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Bổ sung Khung Phản Hồi Chẩn Đoán Thiên Kiến Tự Động (Automated Debias Feedback Card) vào Bảng Phản Tư"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
