@echo off
echo Đang thêm bản nâng cấp Thẻ Ngành học & Nút Phản tư nhanh...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit nâng cấp...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Nâng cấp thẻ Ngành học MajorCard tích hợp Mức lương lộ trình, Cảnh báo rủi ro (Risk Indicator) và Nút Phản tư nhanh (Debias Direct Link)"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
