@echo off
echo Đang thêm bản cập nhật loại bỏ 100% Mock Data...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit chuẩn hóa 100% Supabase DB...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Loại bỏ 100% dữ liệu Mock/LocalStorage, kết nối thuần 100% với Supabase PostgreSQL DB"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
