@echo off
echo Đang thêm bản sửa nút bấm chuyển hướng Lộ trình Hướng nghiệp...
C:\Users\HP\git-portable\cmd\git.exe add .
echo Tạo commit sửa chuyển hướng...
C:\Users\HP\git-portable\cmd\git.exe commit -m "Sửa triệt để logic chuyển hướng useNavigate và window.open cho các nút bấm Chặng trên trang Lộ trình Hướng nghiệp"
echo Đẩy mã nguồn lên GitHub...
C:\Users\HP\git-portable\cmd\git.exe push origin main
